### PR TITLE
[ENGOPS-1114] Mavenization

### PR DESCRIPTION
**Pull request by abaskakau**
Removed old ant+ivy build mechanism
Added new maven build files
Sources was moved to default maven source directories
@smaring @lgrill-pentaho

### CODE REVIEW

**Comment by smaring** [comment]
This looks great.  The only issue with it now will come from Joe our CM guy.  "All project commits NEED to reference a ticket".   If its something really stupid, then you can just reference "[CLEANUP]".  So that one commit for the parent pom version should either be rolled into the Mavenization commit or just prepended with "[CLEANUP]".

**Comment by abaskakau** [comment]
Fixed. You can merge it now

Best Regards,
Andrei Baskakau
Junior Software Maintenance Engineer

EPAM Systems
Minsk office, Belarus
GMT+3

**Comment by abaskakau** [comment]
Adding Steve to CC

Best Regards,
Andrei Baskakau
Junior Software Maintenance Engineer

EPAM Systems
Minsk office, Belarus
GMT+3

From: Andrei Baskakau
Sent: Wednesday, April 29, 2015 16:32
To: 'pentaho/pentaho-mongo-utils'; pentaho/pentaho-mongo-utils
Subject: RE: [pentaho-mongo-utils] [ENGOPS-1114] Mavenization (#38)

Fixed. You can merge it now

Best Regards,
Andrei Baskakau
Junior Software Maintenance Engineer

EPAM Systems
Minsk office, Belarus
GMT+3

**Comment by brosander** [comment]
@abaskakau

1. The message.properties files (and any non-java resources) need to be moved to src/main/resources
2. Please use the maven bundle plugin for the build (https://github.com/pentaho/pentaho-osgi-bundles/blob/future-develop/pentaho-i18n-bundle/pom.xml#L90)

**Comment by abaskakau** [comment]
@brosander please have a look now

**Comment by brosander** [comment]
@abaskakau it looks like there are still properties files in src/main/java, please move them to the appropriate directories in src/main/resources

**Comment by abaskakau** [comment]
@brosander Done, but it seems that tests cannot find this resources. 

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.pentaho.mongo.MongoPropertiesTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.112 sec <<< FAILURE! - in org.pentaho.mongo.MongoPropertiesTest
testBuildsMongoClientOptions(org.pentaho.mongo.MongoPropertiesTest)  Time elapsed: 1.069 sec  <<< ERROR!
java.util.MissingResourceException: Can't find bundle for base name org.pentaho.mongo.messages.messages, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at org.pentaho.mongo.BaseMessages.getString(BaseMessages.java:35)
	at org.pentaho.mongo.MongoPropToOption.readPrefValue(MongoPropToOption.java:88)
	at org.pentaho.mongo.MongoProp$8.setOption(MongoProp.java:184)
	at org.pentaho.mongo.MongoProperties.buildMongoClientOptions(MongoProperties.java:60)
	at org.pentaho.mongo.MongoPropertiesTest.testBuildsMongoClientOptions(MongoPropertiesTest.java:42)

testBuildsMongoClientOptionsDefaults(org.pentaho.mongo.MongoPropertiesTest)  Time elapsed: 0 sec  <<< ERROR!
java.util.MissingResourceException: Can't find bundle for base name org.pentaho.mongo.messages.messages, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1564)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1387)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:773)
	at org.pentaho.mongo.BaseMessages.getString(BaseMessages.java:35)
	at org.pentaho.mongo.MongoPropToOption.readPrefValue(MongoPropToOption.java:88)
	at org.pentaho.mongo.MongoProp$8.setOption(MongoProp.java:184)
	at org.pentaho.mongo.MongoProperties.buildMongoClientOptions(MongoProperties.java:60)
	at org.pentaho.mongo.MongoPropertiesTest.testBuildsMongoClientOptionsDefaults(MongoPropertiesTest.java:56)

**Comment by brosander** [comment]
@smaring that addresses my issues with it, not sure what y'all's merge timeline looks like

**Pull request closed without merging**
