### PR TITLE
PDI-13500 - MongoDB Input "GetDBs" option fails to fetch database information when Authentication is used in MongoDB

### PR DESCRIPTION
**Pull request by kolinus**
What was done:
1)changed the method used for creating credentials
2) updated the driver version

### CODE REVIEW

**Comment by kolinus** [comment]
@kurtwalker , @mkambol , could you please review?

**Comment by kurtwalker** [comment]
@kolinus Why the change to the method call?  I don't recall needing any code changes for the build to pass all tests.  We need everything to continue working with both drivers, I'm worried this change would break that.

**Comment by kolinus** [comment]
@kurtwalker , send you the mail with details

**Comment by bkemper-pentaho** [comment]
Please send them to me as well

Sent from my iPhone

On Apr 28, 2015, at 6:02 AM, Kanstantsin Karneliuk <notifications@github.com<mailto:notifications@github.com>> wrote:


@kurtwalker<https://github.com/kurtwalker> , send you the mail with details

-

**Comment by kolinus** [comment]
@bkemper-pentaho  have sent

**Pull request merged**
